baseURL: https://inhzus.io
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
title: inhzus.io
theme: futu
enableRobotsTXT: true
enableEmoji: true
enableGitInfo: true
hasCJKLanguage: true
googleAnalytics: "G-Q9FKTCTEEV"
imaging:
  quality: 75
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
params:
  author:
    name: inhzus
  keywords: []
  description: ''
  ampLogo: ''
  since: '2019'
  paginate: 100
  dateFormatToUse: Jan 2, 2006
  toc: false
  googleVerification: ''
  microsoftClarity: "jt8wmngepq"
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  Markdown:
    mediaType: text/markdown
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
  page:
    - HTML
    - AMP
    - Markdown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
markup:
  tableOfContents:
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
    parser:
      wrapStandAloneImageWithinParagraph: false
  highlight:
    codeFences: true
    noClasses: false
languages:
  zh-CN:
    disabled: true
    title: Inhzus
    languageCode: zh-CN
    languageName: 简体中文
    menu:
      main:
        - name: 首页
          weight: 10
          identifier: home
          url: /
        - name: 归档
          weight: 20
          identifier: posts
          url: /posts/
        - name: 关于
          weight: 30
          identifier: about
          url: /about/
  en:
    title: Inhzus
    languageCode: en
    languageName: English
    menu:
      main:
        - name: Home
          weight: 10
          identifier: home
          url: /
        - name: Posts
          weight: 20
          identifier: posts
          url: /posts/
        - name: About
          weight: 30
          identifier: about
          url: /about/
