baseurl: "/"
languageCode: "en-us"
title: "Inhzus"
theme: "ivy"
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"

permalinks:
    post: "/post/:filename/"
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Tags"
      url: "/tags/"
      weight: 2
    - name: "Subscribe"
      url: "/index.xml"

params:
  description: "Tech blog of inhzus."
  footer: "&copy; [Inhzus](https://zsuun.com) | [Github](https://github.com/inhzus)"

  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["go", "cpp", "matlab"]
  highlightjsTheme: "github"
