baseurl: "https://inhzus.com"
languageCode: "en-us"
title: "Inhzus"
theme: "ivy"
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
googleAnalytics: "UA-134644252-2"

permalinks:
    posts: "/posts/:filename/"
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Subscribe"
      url: "/index.xml"
taxonomies:
  tag: ""
  category: ""
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    style: github

params:
  description: "Tech blog of inhzus."
  footer: "&copy; [Inhzus](https://zsuun.com) 2020 | [Github](https://github.com/inhzus)"
