baseurl: "https://inhzus.com"
languageCode: "en-us"
title: "Inhzus"
theme: "carpe"
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
googleAnalytics: "G-Q9FKTCTEEV"
disableKinds: ["taxonomy", "term"]

permalinks:
  posts: "/posts/:filename/"
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Subscribe"
      url: "/index.xml"
      weight: 3
    - name: "GitHub"
      url: "https://github.com/inhzus"
      weight: 4
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    noClasses: false

params:
  description: "Tech blog of inhzus."
  footer: |
    &copy; [Inhzus](https://inhzus.io) 2020 | [Github](https://github.com/inhzus)
